### ISSUE TITLE
In Java we don't use printToScreen, so maybe we can use toString(); ?? 

### ISSUE THREAD

**Issue by OliviaImner** [OliviaImner/DogRegister#7] opened 2015-12-08 11:59 UTC

**Comment by OliviaImner** [comment] 2015-12-08 12:01
they use printToScreen in C++

**Comment by jasonserviss** [comment] 2015-12-08 12:13
printToscreen is the name of a method NOT an inbuilt java command. We declare this method and decide what the method is named. We can name it whatever we want and it does NOT matter if the method has the same name as a method in C++, perl, R, python or any other programming language. It does matter that the method does not have the same name as a method in Java (and it does not) since that would be a bit confusing.

**Comment by OliviaImner** [comment] 2015-12-08 12:14
In Java all the classes contain toString as standard. Since all classes in Java inherit from the Object class (which in turn has a toString)

**Comment by OliviaImner** [comment] 2015-12-08 12:15
Aha ok.

**Comment by OliviaImner** [comment] 2015-12-08 12:16
why do they use toString then? All the variable need to be Strings then?

**Comment by jasonserviss** [comment] 2015-12-08 12:34
I am not following these questions at all.... Who is "they", all of WHAT variables need to be strings.... You need to be more specific with your questions!

**Comment by OliviaImner** [comment] 2015-12-08 12:38
why do Java have the toString method then?

**Comment by jasonserviss** [comment] 2015-12-08 12:53
If you look at the example [here](http://stackoverflow.com/questions/29140402/how-do-i-print-my-java-object-without-getting-sometype2f92e0f4) you can see that if you call toString on an object it does NOT print the objects attributes as strings. Instead, it prints something like this: _com.foo.MyType@2f92e0f4_. It says in this post: "_The Object.toString() method returns a fairly ugly looking string, composed of the name of the class, an @ symbol and the hashcode of the object in hexadecimal_".

**Comment by jasonserviss** [comment] 2015-12-08 12:56
What toString is for is described [here](http://www.tutorialspoint.com/java/number_tostring.htm). For making int's into strings (among other things).

**Comment by jasonserviss** [comment] 2015-12-08 12:57
i.e. it is **not** for converting objects, or their attributes, into strings.

**Comment by OliviaImner** [comment] 2015-12-08 13:07
Aha ok, I think I got it, thanks!

**Comment by jasonserviss** [comment] 2015-12-08 13:08
Alright, good. If you got it then close the issue

**Comment by jasonserviss** [comment] 2015-12-08 13:36
# If the issue is resolved you should close it @OliviaImner

**Closed as completed** 2015-12-08 13:37 UTC
Labels: question
