### ISSUE TITLE
I can't understand the for loop in DogRegister. Does it decelerates a new object of the class Dog and the method arraylist? 

### ISSUE THREAD

**Issue by OliviaImner** [OliviaImner/DogRegister#6] opened 2015-12-08 09:05 UTC

**Comment by jasonserviss** [comment] 2015-12-08 09:06
You need to paste the code here so I can see it....

**Comment by OliviaImner** [comment] 2015-12-08 09:08
// 	brings the first value of every new round of the array
		for( int i=0; i<5; i++ ) {
			DogClass currentDog = new DogClass(NameArray[i], BreedArray[i], AgeArray[i], WeightArray[i]);
			currentDog.calculateTailLength(BreedArray[i], AgeArray[i], WeightArray[i]);
			DogArrayList.add(currentDog);

**Comment by jasonserviss** [comment] 2015-12-08 09:26
paste in the arrays that are declared before the for loop starts

**Comment by OliviaImner** [comment] 2015-12-08 09:31
Do you think the comment is ok?

**Comment by jasonserviss** [comment] 2015-12-08 09:34
You need to paste the arrays that are declared before the for loop starts so I can explain to you what is happening! The arrays look like:

String[] NameArray = {something, something...}
String[] BreedArray = {something, something...}
etc.

**Comment by OliviaImner** [comment] 2015-12-08 09:37
ok

**Comment by jasonserviss** [comment] 2015-12-08 09:39
You have to paste them here, in the comments on github so I can see them

**Comment by OliviaImner** [comment] 2015-12-08 09:40
//initial values
    String[] NameArray = {"Fido", "Mary", "John", "Ginger", "Jake"};
    String[] BreedArray = {"tax", "doberman", "mastif", "rottweiler", "colie"};
    int[] AgeArray = {1,2,3,4,5};
    double[] WeightArray = {10.1, 20.1, 30.1, 40.1, 50.1};
    double[] TailLengthArray = {3.7, 2.1, 3.1, 4.1, 5.1};
//make primary register
public ArrayList makePrimaryRegister() {
ArrayList DogArrayList = new ArrayList();

//  brings the first value of every new round of the array
    for( int i=0; i<5; i++ ) {
        DogClass currentDog = new DogClass(NameArray[i], BreedArray[i], AgeArray[i], WeightArray[i]);
        currentDog.calculateTailLength(BreedArray[i], AgeArray[i], WeightArray[i]);
        DogArrayList.add(currentDog);

**Comment by jasonserviss** [comment] 2015-12-08 09:58
Remove this line of code from the program:

double[] TailLengthArray = {3.7, 2.1, 3.1, 4.1, 5.1};

Run the program and see if it still works as expected. Look carefully at the TailLength attribute in the current register when the program first starts.

**Comment by jasonserviss** [comment] 2015-12-08 10:04
Is it working????????

**Comment by OliviaImner** [comment] 2015-12-08 10:09
Yes it works

**Comment by OliviaImner** [comment] 2015-12-08 10:11
So I don't need TailLength as a variable ?

**Comment by jasonserviss** [comment] 2015-12-08 10:15
You did not delete the TailLength attribute (it is NOT a variable!!!!!!!) you deleted the TailLengthArray. We will calculate the TailLength attribute with the method calculateTailLength.

**Comment by jasonserviss** [comment] 2015-12-08 10:17
Here is the for loop with a lot of comments and explanation. If you rename it "explanation.java" and open it in Xcode it will be easier to read. If you don't understand something read it again before you write me more questions!!!!

[explaination.txt](https://github.com/OliviaImner/DogRegister/files/55270/explaination.txt)

**Comment by OliviaImner** [comment] 2015-12-08 10:18
I mean that I deleted the TailLengthArray .. ok

**Comment by jasonserviss** [comment] 2015-12-08 10:21
Yes, good. We calculate the tailLength attribute for each dog in the primary register using the method calculateTailLength so we do not need the values in TailLengthArray.

**Comment by OliviaImner** [comment] 2015-12-08 10:23
No ok. Thank you ..

**Comment by jasonserviss** [comment] 2015-12-08 10:25
You should not close the issue until it is resolved, and unless you understand everything I wrote, the issue is not resolved yet.

**Comment by OliviaImner** [comment] 2015-12-08 10:35
oh ok sorry

**Comment by OliviaImner** [comment] 2015-12-08 10:50
When we use calculateTailLength, why do we need BreedArray[i]?  Because if it is a tax?

**Comment by jasonserviss** [comment] 2015-12-08 10:55
When we write calculateTailLength(NameArray[i], BreedArray[i], etc...) where does BreedArrray[i] get placed before the method is executed?

**Comment by OliviaImner** [comment] 2015-12-08 10:58
oh I see know, never mind .. Its because when we calculate the TailLength in the ClassDog we need to know what breed it is.

**Comment by OliviaImner** [comment] 2015-12-08 11:04
I think i got it know :+1:

**Comment by jasonserviss** [comment] 2015-12-08 11:04
BreedArray[i] becomes Breed in the calculateTailLength method. BreedArray[1] -> Breed. This is because we pass BreedArray[i] as the first parameter when we call the method: 

calculateTailLength(BreedArray[i], etc)

and we can see in the method definition that the first parameter is stored in the "Breed" variable.

public void calculateTailLength(String Breed, int Age, double Weight){
 //body
}

Then if we look at how the "Breed" variable is used in the method, you get the answer to your question.

**Comment by jasonserviss** [comment] 2015-12-08 11:04
Read through my last comment even if you understand now....

**Comment by jasonserviss** [comment] 2015-12-08 11:09
If you are sure you understand everything I wrote then close the issue, otherwise keep it open until you do understand everything.....

**Comment by OliviaImner** [comment] 2015-12-08 11:10
Ok I will read it again.

**Comment by OliviaImner** [comment] 2015-12-08 11:11
Yes understand know.

**Closed as completed** 2015-12-08 11:12 UTC
Labels: question
